### ISSUE TITLE
panic: Duplicated key '_' in struct config.ProjectConfig

### ISSUE THREAD

**Issue by schollz** [goreleaser/releaser#37]
Great project!
I'm trying to use it on my program which has a `main.go`, github.com/schollz/bol. My goreleaser.yml is:

```
repo: schollz/bol
binary_name: bol
```

and I keep getting an error:

```
$ releaser -c goreleaser.yml
panic: Duplicated key '_' in struct config.ProjectConfig [recovered]
        panic: Duplicated key '_' in struct config.ProjectConfig

goroutine 1 [running]:
panic(0x788c40, 0xc042005560)
        C:/Go/src/runtime/panic.go:500 +0x1af
gopkg.in/yaml%2ev1.handleErr(0xc0420918e0)
        C:/Go/work/src/gopkg.in/yaml.v1/yaml.go:28 +0x194
panic(0x788c40, 0xc042005560)
        C:/Go/src/runtime/panic.go:458 +0x251
gopkg.in/yaml%2ev1.(*decoder).mappingStruct(0xc042091898, 0xc04203e6c0, 0x7d9620, 0xc0420c20f0, 0x199, 0x0)
        C:/Go/work/src/gopkg.in/yaml.v1/decode.go:508 +0x507
gopkg.in/yaml%2ev1.(*decoder).mapping(0xc042091898, 0xc04203e6c0, 0x7d9620, 0xc0420c20f0, 0x199, 0x0)
        C:/Go/work/src/gopkg.in/yaml.v1/decode.go:461 +0x863
gopkg.in/yaml%2ev1.(*decoder).unmarshal(0xc042091898, 0xc04203e6c0, 0x7d9620, 0xc0420c20f0, 0x199, 0xc042091830)
        C:/Go/work/src/gopkg.in/yaml.v1/decode.go:261 +0x7b
gopkg.in/yaml%2ev1.(*decoder).document(0xc042091898, 0xc04203e660, 0x7d9620, 0xc0420c20f0, 0x199, 0xc042091848)
        C:/Go/work/src/gopkg.in/yaml.v1/decode.go:273 +0x8b
gopkg.in/yaml%2ev1.(*decoder).unmarshal(0xc042091898, 0xc04203e660, 0x7d9620, 0xc0420c20f0, 0x199, 0x199)
        C:/Go/work/src/gopkg.in/yaml.v1/decode.go:255 +0x152
gopkg.in/yaml%2ev1.Unmarshal(0xc042080d80, 0x23, 0x223, 0x7ab180, 0xc0420c20f0, 0x0, 0x0)
        C:/Go/work/src/gopkg.in/yaml.v1/yaml.go:95 +0x1da
github.com/goreleaser/releaser/config.Load(0xc0420053b0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Go/work/src/github.com/goreleaser/releaser/config/config.go:54 +0xf2
main.main.func1(0xc042040640, 0xc042040640, 0xc042091c27)
        C:/Go/work/src/github.com/goreleaser/releaser/main.go:39 +0x77
github.com/urfave/cli.HandleAction(0x77e500, 0x831440, 0xc042040640, 0xc04203e4e0, 0x0)
        C:/Go/work/src/github.com/urfave/cli/app.go:485 +0xdb
github.com/urfave/cli.(*App).Run(0xc042070d00, 0xc042007fb0, 0x3, 0x3, 0x0, 0x0)
        C:/Go/work/src/github.com/urfave/cli/app.go:259 +0x756
main.main()
        C:/Go/work/src/github.com/goreleaser/releaser/main.go:52 +0x1e4
```

**Comment by caarlos0** [comment]
Sorry, my bad.

Fixed in 4369eb3
